stages:
  - archiving
  - build
  - deploy

archive:
  stage: archiving

  before_script:
    - apt-get update
    - apt-get install zip -y

  script:
    - echo "Archiving lambda code"
    - zip -r $CI_PROJECT_NAME.zip *

  artifacts:
    paths:
      - $CI_PROJECT_NAME.zip


build:
  stage: build
  image: ruby:2.7
  script:
    - gem install bundler
    - bundle update --bundler
    - gem install bundler:1.17.1
    - bundle install --deployment

  artifacts:
    paths:
      - vendor/bundle

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]

  script:
    - echo "Deploying code"
    - aws lambda update-function-code --function-name $LAMBDA_FUNCTION --zip-file fileb://$CI_PROJECT_NAME.zip

  only:
    - main
