stages:
  - build
  - deploy

build:
  stage: build
  image: ruby:2.7
  script:
    - gem install bundler
    - bundle update --bundler
    - gem install bundler:1.17.1
    - bundle install --deployment

  artifacts:
    paths:
      - vendor/bundle

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]

  script:
    - echo "Deploying code"
    - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --region $AWS_REGION --zip-file fileb://$(ls -1t *.zip | head -n 1)

  only:
    - main
